FROM eclipse-temurin:17-jre-alpine

ENV JAVA_OPTS="-Xms512m -Xmx512m -Djava.security.egd=file:/dev/./urandom"

WORKDIR /app

COPY target/kbe-rest-beer-0.0.1-SNAPSHOT.jar ./beer-app.jar

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar beer-app.jar"]